### ISSUE TITLE
Problem when using the agent for deploying code that symlinks are gone and get files with zero length

### ISSUE THREAD

**Issue by rvanhoudt** [continuousphp/deploy-agent#12]
When you use the agent to deploy, he untars the package but the symlinks in that package are gone and are files with zero lenght now

**Comment by ppaulis** [comment]
Thanks for reporting this! A fix for this issue should be available in a few days.

Greetings,
Pascal

**Comment by continuousphptest** [comment]
@rvanhoudt Sorry for the late reply! :-/ The fix will be available for tomorrow morning. I'll keep you updated.

Greetings,
Pascal

**Comment by ppaulis** [comment]
@rvanhoudt Just published version 0.1.3 of the deploy agent with the fix for the symlinks. Sorry again for the delay!

Greetings,
Pascal
