### ISSUE TITLE
Some Docker tips and enhancements

### ISSUE THREAD

**Issue by nasskach** [continuousphp/deploy-agent#19]
Hi,

I just would like to give you some feedbacks about your docker integration.

```
RUN apt-get update && apt-get install -y \
    git \
    vim \
    bzip2 \
    zip \
    libbz2-dev \
    libmcrypt-dev \
    libicu-dev \
    && docker-php-ext-configure mysqli \
    && docker-php-ext-install mysqli pdo_mysql bz2 mcrypt intl
```
- You can add `&& rm -rf /var/lib/apt/lists/*`at the end to remove some cached files... you will save few MB on your images.

`RUN rm -rf /var/app/.git`
- This is not the right way to remove data because they will still present in the previous layer. You should use [.dockerignore file](https://docs.docker.com/engine/reference/builder/#/dockerignore-file) to exclude that directory.

```
RUN cd /var/app; \
    /usr/bin/composer update; \
./scripts/post-create-project
```
- You should use `&&` for chaining commands to avoid silent failures. In general you can use that also for reducing the number of layers by reducing the number of `RUN`instructions.

Thanks.

**Comment by Pierozi** [comment]
Hello @nasskach 

Thanks to you for taking time to share theses enhancement.
I will perform change as soon as possible and let you review.

Thanks.
